Review project
zieeco/project-review-test pull request #1
Opened 2021-06-08 01:05 UTC by zieeco

## Review project

In this project, I:

-  Added index.html file
- Added style.css
- Added a readme file
- Added gitignore file
- ensured there was no linters error

2021-06-08 01:17 UTC, zieeco reviewed
# STATUS: APPROVED 🎉 🥇

**Hi @zieeco ,**

Your project is complete! There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

As described in the Code reviews limits policy you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using this form.

Reviewed by: zieeco

2021-06-08 03:11 UTC, teekaytech requested changes
## Status: Changes Required :warning: :vertical_traffic_light: 

### Hello @zieeco :wave:

__This is a brilliant effort :clap: You've really done an amazing job so far. In this PR, my major highlights include__

- There are no linter errors :100: 
- Your project documentation looks nice :+1: 
- PR title, commit  messages, and summary looks good :+1: 

__However, you need to make some required changes before moving on to the next assignment. Please check my comments below and fix them as appropriate.__

### **Required Changes** :recycle: 

- [ ] You've played well the role of a code reviewer. However, you need to keep the following in mind: 
  - You've used the `Review Changes` feature in GitHub, which is great, but inline comments are missing in your review.
  - This project requires that you add as many inline comments as possible. In the worst-case scenario, you need to add a minimum of 2 comments. Kindly use GitHub features comments as specified [here](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/give_code_review_basics.md), paying special attention to point number 3 (inline comments).
  - I believe you should be able to find at least 2 things that can be improved on in your code. For instance, you can point out that "More semantic HTML tags should be used", "Try to always use class names for CSS selectors completely, and less of ID selectors", etc. These and others can be pointed out in your inline comments; you will definitely find something that could have been done better!

Check an example of an inline comment under the review.

### **Optional Changes** :zap: 
N/A


* * *
**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. You can mention me (@teekaytech) so I can be notified about your comments and respond._

*REMINDER: As described in the [Code reviews limit Policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).*

_**Please make the required changes and submit another review request when you are done.**_

* * *

_Reviewed by:_ [**Taofeek Olalere**](https://github.com/teekaytech)
__Cheers & Happy coding :smiley:__

2021-06-08 03:11 UTC, teekaytech commented on README.md
> +[Live Demo Link]()
Your live demo link is broken. I suggest you deploy your project with [GitHub Pages](https://guides.github.com/features/pages/) or [GitHack](rawcdn.githack.com/). Better still, if you do not want to host your app, you can simply remove the `Live Demo` section of your Readme. This is allowed because deployment is not a requirement of this project, therefore it is safe to remove this section :blush: However, if you wish to leave it, the link must not be broken.

2021-06-08 14:18 UTC, zieeco reviewed
## Required Changes 

Please check my comments below and do all the required changes

Submit for re-review

2021-06-08 14:18 UTC, zieeco commented on index.html
> +      </p>
I think it will be nice if you use more semantic tags on your page. Semantic HTML elements are those that clearly describe their meaning in a human- and machine-readable way.

2021-06-09 09:20 UTC, zieeco commented on README.md
> +[Live Demo Link]()
Thanks. 
I've updated the Live Demo Link

2021-06-09 09:22 UTC, zieeco commented on index.html
> +      <div id="img-caption">
Thanks. 
I've updated the page to use class attribute instead of ID's for multiple elements

2021-06-09 09:24 UTC, zieeco commented on index.html
> +      </p>
Thanks. 
I've updated the page to use more semantic tags to aid SEO.

2021-06-09 13:35 UTC, jubaan approved these changes
Hi @zieeco , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-06-09 14:48 UTC, merged